apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lokalise-v0.1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      version: v0.1.0
  template:
    metadata:
      labels:
        version: v0.1.0
    spec:
      containers:
      - name: nginx-lokalise
        image: nginx-lokalise:v0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5